const ROLES = require("./roles");
const PERMISSIONS = require("./permissions");

module.exports = {

    [ROLES.USER]: [
    ],

    [ROLES.AUTHOR]: [
        PERMISSIONS.CREATE_POST,
    ],

    [ROLES.ADMIN]: [
        PERMISSIONS.CREATE_POST,
        PERMISSIONS.EDIT_ANY_POST,
        PERMISSIONS.DELETE_ANY_POST,

        PERMISSIONS.CREATE_CATEGORY,
        PERMISSIONS.EDIT_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_CATEGORY,

        PERMISSIONS.DELETE_ANY_COMMENT,

        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.VIEW_LOGS,

    ],

    [ROLES.TECH_ADMIN]: [
        PERMISSIONS.CREATE_POST,
        PERMISSIONS.EDIT_ANY_POST,
        PERMISSIONS.DELETE_ANY_POST,

        PERMISSIONS.CREATE_CATEGORY,
        PERMISSIONS.EDIT_ANY_CATEGORY,
        PERMISSIONS.DELETE_ANY_CATEGORY,

        PERMISSIONS.DELETE_ANY_COMMENT,

        PERMISSIONS.MANAGE_ROLES,
        PERMISSIONS.VIEW_LOGS,
    ],
};